'use client';

import { Inter } from "next/font/google";
import Link from 'next/link'
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    <title>Hossain Iban Ehsan</title>
      <body className={inter.className}>

      <div className="nev_area">
        <a href="/" className="nev_btn home_nev_btn">Home</a>
        <a href="/projects" className="nev_btn projects_nev_btn">Projects</a>
        <a href="/about" className="nev_btn about_me_nev_btn">About me</a>
      </div>

      {children}</body>
    </html>
  );
}
